name: CI

on:
  pull_request:

jobs:
  linters:
    name: "Linters"
    runs-on: ubuntu-latest
    steps:
      - name: Check the code out
        uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          key: venv-{{ hashFiles('qsyncer/requirements/*.txt') }}
          restore-keys: |
            venv-

      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: /tmp/pre-commit-cache
          key: pre-commit-v2-{{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-v2-

      - name: Install the Python dependencies
        run: make sync

      - name: Run the code linters
        run: |
          source venv/bin/activate
          pre-commit run --all-files
        env:
          PRE_COMMIT_HOME: /tmp/pre-commit-cache
