name: CI

on:
  pull_request:

jobs:
  linters:
    name: "Linters"
    runs-on: ubuntu-latest
    steps:
      - name: Check the code out
        uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Activate the cache for pip
        uses: actions/cache@v2
        with:
          path: venv
          key: pip-v2-{{ hashFiles('requirements/base.txt') }}-{{ hashFiles('requirements/dev.txt') }}
          restore-keys: |
            pip-v2-{{ hashFiles('requirements/base.txt') }}-{{ hashFiles('requirements/dev.txt') }}
            pip-v2-{{ hashFiles('requirements/base.txt') }}-
            pip-v2-

      - name: Activate the cache for pre-commit
        uses: actions/cache@v2
        with:
          path: /tmp/pre-commit-cache
          key: pre-commit-v1-{{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-v1-{{ hashFiles('.pre-commit-config.yaml') }}
            pre-commit-v1-

      - name: Install the Python dependencies
        run: make sync

      - name: Run the code linters
        run: |
          source venv/bin/activate
          pre-commit run --all-files
        env:
          PRE_COMMIT_HOME: /tmp/pre-commit-cache
